filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/r/*.log
  fields:
    log_topics: lb_core_ngx_t




- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/t/*.log
  fields:
    log_topics: lb_core_ngx_r



output.kafka:
  enabled: true
  hosts: ["kafka1:9092","kafka2:9092","kafka3:9092"]
  topic: '%{[fields][log_topics]}'
