version: '3.5'

networks:
  elk_net:
    external: true

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    container_name: es01
    restart: always
    networks:
      - elk_net
    environment:
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /opt/elasticsearch/data:/usr/share/elasticsearch/data/
      - /opt/elasticsearch/logs:/usr/share/elasticsearch/logs/
      - /opt/elasticsearch/config:/usr/share/elasticsearch/config/
    ports:
      - 9200:9200
