filebeat.inputs:


- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/activity.log
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
  fields:
    log_topics: first-test

output.kafka:
  enabled: true
  hosts: ["kafka:9092"]
  topic: '%{[fields][log_topics]}'
