version: '3.5'

networks:
  net:
    external: true

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es01
    hostname: es01
    restart: always
    networks:
      - net
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/elasticsearch/data:/usr/share/elasticsearch/data/
      - /opt/elasticsearch/logs:/usr/share/elasticsearch/logs/
      - /opt/elasticsearch/config:/usr/share/elasticsearch/config/
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    hostname: kibana
    container_name: kibana
    restart: always
    networks:
      - net
    ports:
      - "5601:5601"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
    image: docker.elastic.co/logstash/logstash:7.16.2
    container_name: logstash
    hostname: logstash
    restart: always
    networks:
      - net
    ports:
      - "5044:5044"
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/logstash/config:/usr/share/logstash/config/
      - /opt/logstash/patterns:/usr/share/logstash/patterns/

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    hostname: filebeat
    container_name: filebeat
    restart: always
    networks:
      - net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /tmp/logs/:/usr/share/filebeat/logs/
