version: '3.5'

networks:
  net:
    external: true

services:
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    container_name: es02
    hostname: es02
    restart: always
    networks:
      net:
        ipv4_address: 172.100.0.102
    environment:
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/elasticsearch2/data:/usr/share/elasticsearch/data/
      - /opt/elasticsearch2/logs:/usr/share/elasticsearch/logs/
      - /opt/elasticsearch2/config:/usr/share/elasticsearch/config/
    ports:
      - 9200:9200
      - 9300:9300
