version:  "3"
networks:
  net:
    external: true
services:
  zookeeper:
    image: sppo55/alex:zookeeper-v1
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - net
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /opt/zookeeper2/conf/zoo.cfg:/opt/apache-zookeeper-3.5.9-bin/conf/zoo.cfg
       - /opt/zookeeper2/log:/opt/apache-zookeeper-3.5.9-bin/log
       - /opt/zookeeper2/data:/opt/apache-zookeeper-3.5.9-bin/data
  kafka:
    image: sppo55/alex:kafka-v1
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
    networks:
      - net
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /opt/kafka2/config:/opt/kafka_2.12-2.6.1/config
       - /opt/kafka2/data:/opt/kafka_2.12-2.6.1/data
       - /opt/kafka2/logs:/opt/kafka_2.12-2.6.1/logs