version: '3.8'
networks:
  elk-net:
    external: true
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    hostname: es01
    environment:
#      - node.name=es01
#      - cluster.name=es-cluster
#      - discovery.seed_hosts=es02,es03
#      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    volumes:
      - /opt/elasticsearch1/data:/usr/share/elasticsearch/data/
      - /opt/elasticsearch1/logs:/usr/share/elasticsearch/logs/
      - /opt/elasticsearch1/config:/usr/share/elasticsearch/config/
    networks:
      - elk-net
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    hostname: es02
    environment:
#      - node.name=es02
#      - cluster.name=es-cluster
#      - discovery.seed_hosts=es01,es03
#      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    volumes:
      - /opt/elasticsearch2/data:/usr/share/elasticsearch/data/
      - /opt/elasticsearch2/logs:/usr/share/elasticsearch/logs/
      - /opt/elasticsearch2/config:/usr/share/elasticsearch/config/
    networks:
      - elk-net
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    hostname: es03
    environment:
#      - node.name=es03
#      - cluster.name=es-cluster
#      - discovery.seed_hosts=es01,es02
#      - cluster.initial_master_nodes=es01,es02,es03
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    volumes:
      - /opt/elasticsearch3/data:/usr/share/elasticsearch/data/
      - /opt/elasticsearch3/logs:/usr/share/elasticsearch/logs/
      - /opt/elasticsearch3/config:/usr/share/elasticsearch/config/
    networks:
      - elk-net

