version: '3.5'

networks:
  elk_net:
    external: true

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    hostname: kibana
    networks:
      - elk_net
    deploy:
      placement:
        constraints: [node.labels.elk == 1]
      restart_policy:
        condition: on-failure
    ports:
      - "5601:5601"
    volumes:
      - /opt/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
